// This file was autogenerated by vendor/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/Application/main.js', ['Application', 'Application.Main'], ['mootools.extras']);
goog.addDependency('../../../../js/lib/mootools/classes/VariableBinding.js', ['VariableBinding'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Array.extras.js', ['Array.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Element.VariableBinding.js', ['Elements.VariableBinding'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Events.extras.js', ['Events.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Object.extras.js', ['Options.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/String.extras.js', ['String.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/mootools.extras.js', ['mootools.extras'], ['Array.extras', 'Elements.VariableBinding', 'Events.extras', 'Options.extras', 'String.extras']);
