// This file was autogenerated by vendor/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/Application/Base/Collection.class.js', ['Collection'], []);
goog.addDependency('../../../../js/Application/Errors/LengthError.js', ['LengthError'], []);
goog.addDependency('../../../../js/Application/Models/Campaign.class.js', ['Campaign'], ['VModel']);
goog.addDependency('../../../../js/Application/Models/Model.js', ['Model'], ['String.extras']);
goog.addDependency('../../../../js/Application/Models/TestModel.class.js', ['TestModel'], ['VModel']);
goog.addDependency('../../../../js/Application/Models/VProperty.class.js', ['VProperty'], []);
goog.addDependency('../../../../js/Application/Models/Validating.js', ['VModel'], ['LengthError', 'Model', 'VProperty']);
goog.addDependency('../../../../js/Application/main.js', ['Application', 'Application.Main'], ['mootools.extras']);
goog.addDependency('../../../../js/Application/test.js', ['Application', 'Application.Test'], ['Campaign', 'TestModel', 'mootools.extras']);
goog.addDependency('../../../../js/lib/mootools/classes/VariableBinding.js', ['VariableBinding'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Array.extras.js', ['Array.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Class.extras.js', ['Class.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Element.VariableBinding.js', ['Elements.VariableBinding'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Events.extras.js', ['Events.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/Object.extras.js', ['Options.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/String.extras.js', ['String.extras'], []);
goog.addDependency('../../../../js/lib/mootools/extras/mootools.extras.js', ['mootools.extras'], ['Array.extras', 'Elements.VariableBinding', 'Events.extras', 'Options.extras', 'String.extras']);
